version: '3.8'

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=task_management
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - MAIL_MAILER=smtp
      - MAIL_HOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=6d66a686a1f838
      - MAIL_PASSWORD=9379c752ceee46
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS="from@example.com"
      - MAIL_FROM_NAME="${APP_NAME}"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  laravel_web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules	
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:9000/api
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
